/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import Dao.IDsLuaChon_DAO;
import Entity.CauHoi;
import Entity.LuaChons;
import service.RmiServiceLocator;

import javax.swing.*;
import java.rmi.RemoteException;
import java.util.ArrayList;

/**
 *
 * @author THANH PHU
 */
public class CauHoiKiemTra extends JPanel {

    /**
     * Creates new form CauHoiKiemTra
     */
    private IDsLuaChon_DAO lc_dao= RmiServiceLocator.getDsLuaChonDao();
    public CauHoiKiemTra() throws RemoteException {
        initComponents();
        
    }
    public CauHoiKiemTra(int cau,CauHoi cauHoi) throws RemoteException {
        initComponents();
        jTextArea1.setText(cauHoi.getCauHoi());
        jLabel1.setText("Câu "+cau);
        ArrayList<LuaChons> dsLuaChon= lc_dao.getDSLuaChonTheoMa(cauHoi.getMaCauHoi());
        ratioExam1.updateRatio(dsLuaChon.get(0).getLuaChon());
        ratioExam2.updateRatio(dsLuaChon.get(1).getLuaChon());
        ratioExam3.updateRatio(dsLuaChon.get(2).getLuaChon());
        ratioExam4.updateRatio(dsLuaChon.get(3).getLuaChon());
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new ButtonGroup();
        roundedPanel1 = new RoundedPanel();
        jLabel1 = new JLabel();
        jScrollPane1 = new JScrollPane();
        jTextArea1 = new JTextArea();
        ratioExam1 = new RatioExam();
        ratioExam2 = new RatioExam("B","Đáp án");
        ratioExam3 = new RatioExam("C","Đáp án");
        ratioExam4 = new RatioExam("D","Đáp án");

        roundedPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Câu 1");

        jScrollPane1.setVerticalScrollBar(new ScrollBarCustom());

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(246, 246, 246));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        buttonGroup1.add(ratioExam1);
        ratioExam1.setText("ratioExam1");

        buttonGroup1.add(ratioExam2);
        ratioExam2.setText("ratioExam1");

        buttonGroup1.add(ratioExam3);
        ratioExam3.setText("ratioExam1");

        buttonGroup1.add(ratioExam4);
        ratioExam4.setText("ratioExam1");

        GroupLayout roundedPanel1Layout = new GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(ratioExam1, GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
            .addComponent(ratioExam2, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ratioExam3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundedPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, GroupLayout.Alignment.TRAILING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(ratioExam4, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ratioExam1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ratioExam2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ratioExam3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ratioExam4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(roundedPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(roundedPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ButtonGroup buttonGroup1;
    private JLabel jLabel1;
    private JScrollPane jScrollPane1;
    private JTextArea jTextArea1;
    private RatioExam ratioExam1;
    private RatioExam ratioExam2;
    private RatioExam ratioExam3;
    private RatioExam ratioExam4;
    private RoundedPanel roundedPanel1;
    // End of variables declaration//GEN-END:variables
}
