/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import java.awt.*;

/**
 *
 * @author Admin
 */
public class GroupCard extends javax.swing.JPanel {

    /**
     * Creates new form GroupCard
     */
    public GroupCard() {
        initComponents();
        card1.setColor1(Color.decode("#ffffff"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new RoundedPanel();
        title = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        card3 = new Card();
        card1 = new Card();
        card2 = new Card();
        card5 = new Card();
        card4 = new Card();
        card6 = new Card();

        setLayout(new BorderLayout());

        roundedPanel1.setBackground(new Color(61, 141, 122));
        roundedPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        roundedPanel1.setLayout(new FlowLayout(FlowLayout.LEADING));

        title.setFont(new Font("Segoe UI", 1, 15)); // NOI18N
        title.setForeground(new Color(255, 255, 255));
        title.setText("Title");
        roundedPanel1.add(title);

        add(roundedPanel1, BorderLayout.PAGE_START);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel3.setLayout(new GridLayout(2, 3, 10, 10));
        jPanel3.add(card3);
        jPanel3.add(card1);

        card2.setColor1(new Color(0, 153, 153));
        jPanel3.add(card2);
        jPanel3.add(card5);
        jPanel3.add(card4);
        jPanel3.add(card6);

        add(jPanel3, BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Card card1;
    private Card card2;
    private Card card3;
    private Card card4;
    private Card card5;
    private Card card6;
    private javax.swing.JPanel jPanel3;
    private RoundedPanel roundedPanel1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
