/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author THANH PHU
 */
public class ThongKeCard extends JPanel {

    /**
     * Creates new form ThongKeCard
     */
    public ThongKeCard() {
        initComponents();
    }
    public ThongKeCard(String color1,String color2,String bg, String num, String icon, String title, int per){
        
        initComponents();
        jLabel1.setText(num);
        jLabel2.setIcon(new ImageIcon(getClass().getResource("/Image/"+icon+".png")));
        roundedGradientPanel1.setColor1(Color.decode("#"+color1));
        roundedGradientPanel1.setColor2(Color.decode("#"+color2));
        jLabel3.setText(title);
        circlePanel1.setPercentage(per);
        circlePanel1.setBackgroundCircleColor(bg);
//        roundedPanel1.setBackground(Color.decode("#"+bg));
    }
    public void updateCard(String color1,String color2,String bg, String num, String icon, String title, int per){
        initComponents();
        jLabel1.setText(num);
        jLabel2.setIcon(new ImageIcon(getClass().getResource("/Image/"+icon+".png")));
        roundedGradientPanel1.setColor1(Color.decode("#"+color1));
        roundedGradientPanel1.setColor2(Color.decode("#"+color2));
        jLabel3.setText(title);
        circlePanel1.setPercentage(per);
        circlePanel1.setBackgroundCircleColor(bg);
//        roundedPanel1.setBackground(Color.decode("#"+bg));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedGradientPanel1 = new RoundedGradientPanel();
        roundedPanel1 = new RoundedPanel();
        circlePanel1 = new CirclePanel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();

        setOpaque(false);

        roundedGradientPanel1.setColor1(new Color(231, 72, 136));
        roundedGradientPanel1.setColor2(new Color(136, 95, 191));
        roundedGradientPanel1.setOpaque(false);

        roundedPanel1.setBackground(new Color(255, 255, 255));
        roundedPanel1.setPreferredSize(new Dimension(100, 10));

        GroupLayout roundedPanel1Layout = new GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        circlePanel1.setOpaque(false);

        jLabel1.setBackground(new Color(255, 255, 255));
        jLabel1.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setText("jLabel1");

        GroupLayout circlePanel1Layout = new GroupLayout(circlePanel1);
        circlePanel1.setLayout(circlePanel1Layout);
        circlePanel1Layout.setHorizontalGroup(
            circlePanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(circlePanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        circlePanel1Layout.setVerticalGroup(
            circlePanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(circlePanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new ImageIcon(getClass().getResource("/Image/icons8-class-50.png"))); // NOI18N

        jLabel3.setBackground(new Color(255, 255, 255));
        jLabel3.setFont(new Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setForeground(new Color(255, 255, 255));
        jLabel3.setText("jLabel3");

        GroupLayout roundedGradientPanel1Layout = new GroupLayout(roundedGradientPanel1);
        roundedGradientPanel1.setLayout(roundedGradientPanel1Layout);
        roundedGradientPanel1Layout.setHorizontalGroup(
            roundedGradientPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, roundedGradientPanel1Layout.createSequentialGroup()
                .addGroup(roundedGradientPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(roundedGradientPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(roundedPanel1, GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
                    .addGroup(roundedGradientPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(roundedGradientPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(circlePanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        roundedGradientPanel1Layout.setVerticalGroup(
            roundedGradientPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, roundedGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roundedGradientPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(circlePanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGroup(GroupLayout.Alignment.TRAILING, roundedGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 62, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roundedPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(roundedGradientPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(roundedGradientPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CirclePanel circlePanel1;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private RoundedGradientPanel roundedGradientPanel1;
    private RoundedPanel roundedPanel1;
    // End of variables declaration//GEN-END:variables
}
